// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function GetFirstFile(arg1:string):Promise<string>;

export function PreviewCSVFile(arg1:string):Promise<Array<handlers.LogEntry>>;

export function SelectFile():Promise<string>;
