// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFirstFile(arg1) {
  return window['go']['backend']['App']['GetFirstFile'](arg1);
}

export function PreviewCSVFile(arg1) {
  return window['go']['backend']['App']['PreviewCSVFile'](arg1);
}

export function SelectFile() {
  return window['go']['backend']['App']['SelectFile']();
}
